### ISSUE TITLE
@everyone config disable dosen't work

### ISSUE THREAD

**Issue by EvieTheOwl** [Geek202/TomsServerUtils#15]
```toml
# Allowed mentions for chat messages being forwarded to Discord
[discordBot.allowedMentions]
    # Allow @everyone and @here
    everyone = false
    # Allow mentioning users
    users = false
    # Allow mentioning roles
    roles = false
```
  
With the following options a player can still use @everyone ingame. Re-created on the Tiny Tater Test creative server
